volumes:
  papermc_data:
    name: papermc_data

services:
  papermc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: AUTO_CURSEFORGE
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/cursed-walking-a-modern-zombie-apocalypse/files/5339312
      CF_SLUG: cursed-walking-a-modern-zombie-apocalypse
      CF_FILE_ID: 5339312
      CF_API_KEY: ${API_KEY}
      VERSION: 1.20.1
      CONSOLE: 'true'
      ONLINE_MODE: 'false'

    container_name: papermc
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - papermc_data:/data

    ports:
      - "25565:25565"
